# Lab 4: Coffee Lovers Unite

# Coffee Lovers Unite!

In [39]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
import re

# Scrape the Location Counts

1. Use the beautifulsoup library to scrape the data (from menuism.com like the link above) on state names and corresponding number of store locations, for the following chains:

Starbucks

Dunkin’ Donuts

Peet’s Coffee & Tea

Tim Horton’s

Panera Bread

Caribou Coffee

Au Bon Pain

The Coffee Bean & Tea Leaf

McDonald’s

Due to the menuism site being down I was only able to webscrape for the following few coffee chain brands. A similar code structure should work for the rremaining coffee chain brands when the site is back up.

## Starbucks

In [40]:
response = requests.get("https://www.menuism.com/restaurant-locations/starbucks-coffee-39564")


# Parse the HTML using BeautifulSoup
soup_starbucks = BeautifulSoup(response.content, 'html.parser')

# Find all the list items containing Starbucks Coffee locations
locations_list = soup_starbucks.find_all("div", attrs={"class":"card popular-cities-box"})[0:]



In [41]:
state_locations = []

for location in locations_list:
    location_names = location.find_all("li", attrs={"class":""})  # Use find_all here
    for location_name in location_names:
        state_name = location_name.get_text(strip=True)

        # Split the text at " Starbucks Coffee locations " and parentheses
        expression = re.split(r' Starbucks Coffee locations \((\d+)\)', state_name)

        # The first part is the state name, and the second part is the number of locations (if the string format is consistent)
        state = expression[0].strip()  # (The strip() is used to remove any leading/trailing white spaces)
        num_locations = int(expression[1]) if len(expression) > 1 else None  # Convert the string to an integer
        state_locations.append({"State":state,"Number of Locations":num_locations})

pd.DataFrame(state_locations)

Empty DataFrame
Columns: []
Index: []

## Dunkin' Donuts

In [42]:
response = requests.get("https://www.menuism.com/restaurant-locations/dunkin-donuts-181624")


# Parse the HTML using BeautifulSoup
soup_dunkin = BeautifulSoup(response.content, 'html.parser')

# Find all the list items containing Starbucks Coffee locations
locations_list_dd = soup_dunkin("div", attrs={"class":"card popular-cities-box"})[0:]


locations_list_dd

[]

In [43]:
state_locations = []

for location in locations_list_dd:
    location_names = location.find_all("li", attrs={"class":""})  # Use find_all here
    for location_name in location_names:
        state_name = location_name.get_text(strip=True)

        # Split the text at " Starbucks Coffee locations " and parentheses
        expression = re.split(r' Dunkin Donuts Coffee locations \((\d+)\)', state_name)

        # The first part is the state name, and the second part is the number of locations (if the string format is consistent)
        state = expression[0].strip()  # (The strip() is used to remove any leading/trailing white spaces)
        num_locations = int(expression[1]) if len(expression)> 1 else None  # Convert the string to an integer
        state_locations.append({"State" :state, "Number of Locations" :num_locations})

pd.DataFrame(state_locations)

Empty DataFrame
Columns: []
Index: []

## Caribou Coffee

In [44]:
response = requests.get("https://www.menuism.com/restaurant-locations/caribou-coffee-164861")

# Parse the HTML using BeautifulSoup
soup_caribou = BeautifulSoup(response.content, 'html.parser')

# Find all the list items containing Starbucks Coffee locations
locations_list_cc = soup_caribou("div", attrs={"class":"card popular-cities-box"})[0:]


locations_list_cc

[]

In [45]:
state_locations = []

for location in locations_list_dd:
    location_names = location.find_all("li", attrs={"class":""})  # Use find_all here
    for location_name in location_names:
        state_name = location_name.get_text(strip=True)

        # Split the text at " Starbucks Coffee locations " and parentheses
        expression = re.split(r' Caribou Coffee locations \((\d+)\)', state_name)

        # The first part is the state name, and the second part is the number of locations (if the string format is consistent)
        state = expression[0].strip()  # (The strip() is used to remove any leading/trailing white spaces)
        num_locations = int(expression[1]) if len(expression)> 1 else None  # Convert the string to an integer
        state_locations.append({"State" :state, "Number of Locations" :num_locations})

pd.DataFrame(state_locations)

Empty DataFrame
Columns: []
Index: []

## Au Bon Pain

In [46]:
response = requests.get("https://www.menuism.com/restaurant-locations/au-bon-pain-69342")


# Parse the HTML using BeautifulSoup
soup_aubonpain = BeautifulSoup(response.content, 'html.parser')

# Find all the list items containing Starbucks Coffee locations
locations_list_au = soup_aubonpain("div", attrs={"class":"card popular-cities-box"})[0:]


locations_list_au

[]

In [47]:
state_locations = []

for location in locations_list_au:
    location_names = location.find_all("li", attrs={"class":""})  # Use find_all here
    for location_name in location_names:
        state_name = location_name.get_text(strip=True)

        # Split the text at " Starbucks Coffee locations " and parentheses
        expression = re.split(r' Au Bon Pain Coffee locations \((\d+)\)', state_name)

        # The first part is the state name, and the second part is the number of locations (if the string format is consistent)
        state = expression[0].strip()  # (The strip() is used to remove any leading/trailing white spaces)
        num_locations = int(expression[1]) if len(expression)> 1 else None  # Convert the string to an integer
        state_locations.append({"State" :state, "Number of Locations" :num_locations})

pd.DataFrame(state_locations)

Empty DataFrame
Columns: []
Index: []

2. Write a function stateabb() that takes a state name (assume it’s spelled correctly) and converts it to its state abbreviation. This can be a very simple function.

In [48]:
def stateabb(state_name):
    # Dictionary of state names and their corresponding abbreviations
    state_abbreviations = {
        'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR', 'California': 'CA',
        'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE', 'Florida': 'FL', 'Georgia': 'GA',
        'Hawaii': 'HI', 'Idaho': 'ID', 'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA',
        'Kansas': 'KS', 'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD',
        'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS', 'Missouri': 'MO',
        'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV', 'New Hampshire': 'NH', 'New Jersey': 'NJ',
        'New Mexico': 'NM', 'New York': 'NY', 'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH',
        'Oklahoma': 'OK', 'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC',
        'South Dakota': 'SD', 'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT',
        'Virginia': 'VA', 'Washington': 'WA', 'West Virginia': 'WV', 'Wisconsin': 'WI', 'Wyoming': 'WY'
    }

    # Return the corresponding abbreviation or None if the state name is not found
    return state_abbreviations.get(state_name, None)


In [49]:
# Testing
print(stateabb("Massachusetts"))  # Should print "TX"

MA


3. Parse, merge and tidy your data so that you have a row for each state and two columns: state abbrevation, location count.

In [50]:
df_lab4_scraped = pd.read_csv('/content/df_lab4_scraped.csv')
df_lab4_scraped

State Coffee Chain State Abbreviation  Location Count  Population
0           Alaska    Starbucks                 AK              24      733391
1          Alabama    Starbucks                 AL              73     5024279
2         Arkansas    Starbucks                 AR              33     3011524
3          Arizona    Starbucks                 AZ             279     7151502
4       California    Starbucks                 CA            2362    39538223
..             ...          ...                ...             ...         ...
264        Vermont   McDonald's                 VT              30      643077
265     Washington   McDonald's                 WA             326     7705281
266      Wisconsin   McDonald's                 WI             353     5893718
267  West Virginia   McDonald's                 WV             107     1793716
268        Wyoming   McDonald's                 WY              34      576851

[269 rows x 5 columns]

# Supplemental Data

4. Scrape the state names and populations from this wikipedia page. Convert the state names to abbreviations and merge these data with your coffee dataset.

In [51]:
# scraping state names and populations from the wiki page
wiki = requests.get("https://simple.wikipedia.org/wiki/List_of_U.S._states_by_population")

soup_wiki = BeautifulSoup(wiki.content, 'html.parser')
#soup_wiki.find_all('tr')

In [52]:
wiki = requests.get("https://simple.wikipedia.org/wiki/List_of_U.S._states_by_population")


soup_wiki = BeautifulSoup(wiki.content, 'html.parser')

states_data = []
for row in soup_wiki.find_all('tr')[1:]:
    statename = row.find_all('td')[2].text.strip("\n")
    state_population = row.find_all('td')[3].text.strip("\n")
    states_data.append({"State": statename, "Population": state_population})

states_df = pd.DataFrame(states_data).head()
states_df

State  Population
0     California  39,538,223
1          Texas  29,145,505
2        Florida  21,538,187
3       New York  20,201,249
4   Pennsylvania  13,002,700

In [53]:
# Applying the provided stateabb function
states_df['Abbreviation'] = states_df['State'].apply(stateabb)


states_df

State  Population Abbreviation
0     California  39,538,223         None
1          Texas  29,145,505         None
2        Florida  21,538,187         None
3       New York  20,201,249         None
4   Pennsylvania  13,002,700         None

5. Find the revenue, stock price, or your financial metric of choice for each of the companies listed above (if you can find a website to scrape these from that’s great!…but it’s okay if you manually enter these). Merge these values into your big dataset. Note: these values may be repeated for each state.

In [54]:
# Creating the stock prices dictionary
stock_prices = {
    "Starbucks": 92.02,
    "Dunkin' Donuts": 106.48,
    "Peet's Coffee & Tea": 69.12,
    "Tim Horton's": 70.99,
    "Panera Bread": 314.93,
    "Caribou Coffee": 16.49,
    "Au Bon Pain": 168,
    "The Coffee Bean & Tea Leaf": 74.32,
    "McDonald's": 255.76
}

# Merge the stock prices with the scraped dataset

df_lab4_scraped['Stock Price'] = df_lab4_scraped['Coffee Chain'].map(stock_prices)
df_lab4_scraped


State Coffee Chain State Abbreviation  Location Count  \
0           Alaska    Starbucks                 AK              24   
1          Alabama    Starbucks                 AL              73   
2         Arkansas    Starbucks                 AR              33   
3          Arizona    Starbucks                 AZ             279   
4       California    Starbucks                 CA            2362   
..             ...          ...                ...             ...   
264        Vermont   McDonald's                 VT              30   
265     Washington   McDonald's                 WA             326   
266      Wisconsin   McDonald's                 WI             353   
267  West Virginia   McDonald's                 WV             107   
268        Wyoming   McDonald's                 WY              34   

     Population  Stock Price  
0        733391        92.02  
1       5024279        92.02  
2       3011524        92.02  
3       7151502        92.02  
4      39538223        92.02  
..          ...          ...  
264      643077       255.76  
265     7705281       255.76  
266     5893718       255.76  
267     1793716       255.76  
268      576851       255.76  

[269 rows x 6 columns]

6. Create a region variable in your dataset according to the scheme on this wikipedia page: Northeast, Midwest, South, West. You do not need to scrape this information.

In [55]:
# Using a state-to-region mapping dictionary
state_to_region_dict = {
    # Northeast
    'Connecticut': 'Northeast',
    'Maine': 'Northeast',
    'Massachusetts': 'Northeast',
    'New Hampshire': 'Northeast',
    'Rhode Island': 'Northeast',
    'Vermont': 'Northeast',
    'New Jersey': 'Northeast',
    'New York': 'Northeast',
    'Pennsylvania': 'Northeast',

    # Midwest
    'Illinois': 'Midwest',
    'Indiana': 'Midwest',
    'Michigan': 'Midwest',
    'Ohio': 'Midwest',
    'Wisconsin': 'Midwest',
    'Iowa': 'Midwest',
    'Kansas': 'Midwest',
    'Minnesota': 'Midwest',
    'Missouri': 'Midwest',
    'Nebraska': 'Midwest',
    'North Dakota': 'Midwest',
    'South Dakota': 'Midwest',

    # South
    'Delaware': 'South',
    'Florida': 'South',
    'Georgia': 'South',
    'Maryland': 'South',
    'North Carolina': 'South',
    'South Carolina': 'South',
    'Virginia': 'South',
    'Washington, D.C.': 'South',
    'West Virginia': 'South',
    'Alabama': 'South',
    'Kentucky': 'South',
    'Mississippi': 'South',
    'Tennessee': 'South',
    'Arkansas': 'South',
    'Louisiana': 'South',
    'Oklahoma': 'South',
    'Texas': 'South',

    # West
    'Arizona': 'West',
    'Colorado': 'West',
    'Idaho': 'West',
    'Montana': 'West',
    'Nevada': 'West',
    'New Mexico': 'West',
    'Utah': 'West',
    'Wyoming': 'West',
    'Alaska': 'West',
    'California': 'West',
    'Hawaii': 'West',
    'Oregon': 'West',
    'Washington': 'West'
}

# apply the mapping to the CSV dataset
df_lab4_scraped['Region'] = df_lab4_scraped['State'].map(state_to_region_dict)
df_lab4_scraped

State Coffee Chain State Abbreviation  Location Count  \
0           Alaska    Starbucks                 AK              24   
1          Alabama    Starbucks                 AL              73   
2         Arkansas    Starbucks                 AR              33   
3          Arizona    Starbucks                 AZ             279   
4       California    Starbucks                 CA            2362   
..             ...          ...                ...             ...   
264        Vermont   McDonald's                 VT              30   
265     Washington   McDonald's                 WA             326   
266      Wisconsin   McDonald's                 WI             353   
267  West Virginia   McDonald's                 WV             107   
268        Wyoming   McDonald's                 WY              34   

     Population  Stock Price     Region  
0        733391        92.02       West  
1       5024279        92.02      South  
2       3011524        92.02      South  
3       7151502        92.02       West  
4      39538223        92.02       West  
..          ...          ...        ...  
264      643077       255.76  Northeast  
265     7705281       255.76       West  
266     5893718       255.76    Midwest  
267     1793716       255.76      South  
268      576851       255.76       West  

[269 rows x 7 columns]

# Analyze

7. Assess and comment on the prevalence of each chain. Some questions to consider (you don’t need to answer all of these and you may come up with your own):
  Are some of these chains more prevalent in certain states than others? Possibly despite having less stores overall? Same questions for regions instead of states.

  How does your chosen financial metric change by state and region for each chain? For example, having 5 stores in California is very different from having 5 stores in Wyoming.

  Does the distribution of each chain’s stores match population distribution, by both state/region?

  Do the financial data match what you’d expect based on the number and locations of the stores? Why or why not?

In [61]:
# Calculate the total number of stores for each chain
total_stores = df_lab4_scraped['Coffee Chain'].value_counts()
#df_lab4_scraped['TotalStores'] = df_lab4_scraped['Coffee Chain'].value_counts()

# Group by state and coffee chain, then count occurrences
grouped_data = df_lab4_scraped.groupby(['State', 'Coffee Chain']).size().reset_index(name='StateCount')

# Normalize the counts by the total number of stores for each chain
grouped_data['NormalizedCount'] = grouped_data.apply(lambda row: row['StateCount'] / total_stores[row['Coffee Chain']], axis=1)

# Sort and filter to find chains that are more prevalent in specific states
outliers = grouped_data.sort_values(by='NormalizedCount', ascending=False)

#grouped_data.sort_values(by='NormalizedCount', ascending=False)

grouped_data


State    Coffee Chain  StateCount  NormalizedCount
0      Alabama  Dunkin' Donuts           1         0.022222
1      Alabama      McDonald's           1         0.019608
2      Alabama    Panera Bread           1         0.021739
3      Alabama       Starbucks           1         0.019608
4       Alaska      McDonald's           1         0.019608
..         ...             ...         ...              ...
264  Wisconsin      McDonald's           1         0.019608
265  Wisconsin    Panera Bread           1         0.021739
266  Wisconsin       Starbucks           1         0.019608
267    Wyoming      McDonald's           1         0.019608
268    Wyoming       Starbucks           1         0.019608

[269 rows x 4 columns]

**Which 5 chains are the most prevalent in California and New York?**

In [66]:
# Filter data for California and New York
ca_ny_data = df_lab4_scraped[df_lab4_scraped['State Abbreviation'].isin(['CA', 'NY'])]

In [67]:
# Group by Coffee Chain and sum the location counts
chain_counts_ca_ny = ca_ny_data.groupby(['Coffee Chain']).agg({'Location Count': 'sum'}).reset_index()

# Sort data by location count and select top 5 chains
top_5_chains_ca_ny = chain_counts_ca_ny.sort_values(by='Location Count', ascending=False).head(5)

top_5_chains_ca_ny

Coffee Chain  Location Count
5                   Starbucks            2854
2                  McDonald's            2434
1              Dunkin' Donuts            1068
3                Panera Bread             354
6  The Coffee Bean & Tea Leaf             175

**How does the stock price change by state and region for each chain?**

In [68]:
#Descriptive Statistics by State and Chain
state_chain_stats = df_lab4_scraped.groupby(['State', 'Coffee Chain'])['Stock Price'].describe()

# Descriptive Statistics by Region and Chain
region_chain_stats = df_lab4_scraped.groupby(['Region', 'Coffee Chain'])['Stock Price'].describe()

# Print results
print("Descriptive Statistics by State and Chain:\n", state_chain_stats)
print("\nDescriptive Statistics by Region and Chain:\n", region_chain_stats)

Descriptive Statistics by State and Chain:
                           count    mean  std     min     25%     50%     75%  \
State     Coffee Chain                                                         
Alabama   Dunkin' Donuts    1.0  106.48  NaN  106.48  106.48  106.48  106.48   
          McDonald's        1.0  255.76  NaN  255.76  255.76  255.76  255.76   
          Panera Bread      1.0  314.93  NaN  314.93  314.93  314.93  314.93   
          Starbucks         1.0   92.02  NaN   92.02   92.02   92.02   92.02   
Alaska    McDonald's        1.0  255.76  NaN  255.76  255.76  255.76  255.76   
...                         ...     ...  ...     ...     ...     ...     ...   
Wisconsin McDonald's        1.0  255.76  NaN  255.76  255.76  255.76  255.76   
          Panera Bread      1.0  314.93  NaN  314.93  314.93  314.93  314.93   
          Starbucks         1.0   92.02  NaN   92.02   92.02   92.02   92.02   
Wyoming   McDonald's        1.0  255.76  NaN  255.76  255.76  255.76  255.76

Based on the results, the dataset provides a regional breakdown of the stock prices for different coffee chains. The results show that within each region, the stock prices of the chains remain consistent, reflecting the state-level analysis. For example in the Midwest, Starbucks, McDonald's, and Panera Bread have stock prices of $92.02, $255.76, and $314.93 respectively. In the Northeast, the stock prices for these chains remain the same as in the Midwest. We see the same pattern in the South and West regions.

# Automate

Convert your code for Exercises 1-3 above to a function that takes a single argument: the menuism URL. This function should

Scrape the information on state names and corresponding number of store locations on the webpage specified

Extract the name of the company from either the URL specified or the webpage

Return a clean, organized dataset that has three columns: state abbreviation, location count, company name. Company name will likely be repeated on every row.

In [ ]:
def locations_by_state(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

    # Extract coffee shop name from the <h3> tag
    h3_text = soup.find('h3').get_text(strip=True)
    match = re.search(r'\d+ (.+?) Locations', h3_text)
    if match:
        coffee_shop_name = match.group(1)
    else:
        coffee_shop_name = "Unknown Shop"  # Default name if not found in HTML

    # Find all the list items containing restaurant locations
    locations_list = soup.find_all("div", attrs={"class":"card popular-cities-box"})

    state_locations = []
    for location in locations_list:
        location_names = location.find_all("li", attrs={"class":""})
        for location_name in location_names:
            state_name_text = location_name.get_text(strip=True)

            # Using regex to extract state name and number of locations
            match = re.match(r'(\w+).*\((\d+)\)', state_name_text)
            if match:
                state, num_locations = match.groups()
                state_abbr = stateabb(state)

                state_locations.append({
                    "Company Name": coffee_shop_name,
                    "State": state_abbr,
                    "Number of Locations": int(num_locations)
                })

    # Convert the state_locations list to a  DataFrame
    df = pd.DataFrame(state_locations)
    return df


In [ ]:
locations_by_state("https://www.menuism.com/restaurant-locations/dunkin-donuts-181624")